[package]
name = "motd"
version = "0.4.0"
edition = "2024"

[features]
image = ["dep:viuer"]
image-sixel = ["image", "viuer/sixel"]

[dependencies]
dirs = "6.0.0"
rand = "0.9.2"
termcolor = "1.4.1"
viuer = { version = "0.11.0", optional = true, features = ["print-file"] }
